// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5122.robot.subsystems;

import org.usfirst.frc.team5122.robot.OI;
import org.usfirst.frc.team5122.robot.RobotMap;
import org.usfirst.frc.team5122.robot.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Shooter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController leftRotator = RobotMap.shooterLeftRotator;
    SpeedController rightRotator = RobotMap.shooterRightRotator;
    
    SpeedController leftShooter = RobotMap.shooterLeftShooter;
    SpeedController rightShooter = RobotMap.shooterRightShooter;
    
    DigitalInput rotatorBottomLimit = RobotMap.rotatorBottomLimit;
    
    Solenoid Pusher = RobotMap.shooterPusher;
    
    Encoder rotatorEncoder = RobotMap.rotatorEncoder;
    
    double rotatorSpeed;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    // FIRE BALL METHODS
    
    public void intakeOn() {
    	if (!OI.jS2.get()) {
    		leftShooter.set(-.75);
    		rightShooter.set(.75);
    	}
    }
    
    public void intakeOff() {
    		leftShooter.set(0);
    		rightShooter.set(0);
    }
    
    public void fire() {
    	if (!OI.jS1.get()) {
    		leftShooter.set(1);
    		rightShooter.set(-1);
    	}
    }
    
    // ROTATOR METHODS
    
    public void rotate(Joystick js) {
        
    	// If rotator is at bottom and joystick is positive.
    	if (rotatorBottomLimit.get()) {
    		SmartDashboard.putBoolean("Rotator on Bottom Limit", true);
    		if (js.getRawAxis(1) > 0) {
    			moveRotator(js);
    		}
    	}
    	else if (!rotatorBottomLimit.get()) {
    		SmartDashboard.putBoolean("Rotator on Bottom Limit", false);
    		moveRotator(js);
    	}
    	else {
    		stopRotation();
    	}
    }
    
    private void moveRotator (Joystick js) {
    	if (js.getRawAxis(1) < 0) {
			leftRotator.set(-.6*js.getRawAxis(1));
			rightRotator.set(.6*js.getRawAxis(1));
			
			rotatorSpeed = js.getRawAxis(1);
			
    	}
    	else if (js.getRawAxis(1) > 0) {
			leftRotator.set(-0.9*js.getRawAxis(1));	    // Negative so both spin in same direction.
			rightRotator.set(0.9*js.getRawAxis(1));
			
			rotatorSpeed = js.getRawAxis(1);
		}
    	else {
    		stopRotation();
    	}
    }
    
    public void stopRotation() {
    	if (rotatorSpeed > 0) {
    		rotatorSpeed -= 0.1;
    		leftRotator.set(-rotatorSpeed);
			rightRotator.set(rotatorSpeed);
    	}
    	leftRotator.set(0);
    	rightRotator.set(0);
    }
    
    
    public void resetEncoder() {
    	rotatorEncoder.reset();
    }
    
    public double getDistance() {
    	SmartDashboard.putNumber("Rotator Encoder Rotations", rotatorEncoder.getDistance());
    	return rotatorEncoder.getDistance();
    }
    
    // PUSHER METHODS
    
    public void push() {
    	Pusher.set(true);
    }
    
    public void restractPusher() {
    	Pusher.set(false);
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new Rotate());
    }
}

