// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5122.robot;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc.team5122.robot.commands.*;
import org.usfirst.frc.team5122.robot.commands.autoComponents.*;
import org.usfirst.frc.team5122.robot.commands.autoModes.*;
import org.usfirst.frc.team5122.robot.commands.autoModes.A_Lowbar;
import org.usfirst.frc.team5122.robot.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command autonomousCommand;
    SendableChooser autoModeChooser;

    NetworkTable table;
    
    public static OI oi;
    public static Drivetrain drivetrain;
    public static Shooter shooter;
    public static Lift lift;
    
    public Robot(){
    	super();
    	table = NetworkTable.getTable("GRIP/VisionContours");
    }

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    	RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrain = new Drivetrain();
        shooter = new Shooter();
        lift = new Lift();
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands 
        //(which it very likely will), subsystems are not guaranteed to be 
        // constructed yet. Thus, their requires() statements may grab null 
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // instantiate the command used for the autonomous period
        autoModeChooser = new SendableChooser();
        autoModeChooser.addObject("Cheval Center", new A_Cheval("center"));
        autoModeChooser.addObject("Cheval Right", new A_Cheval("right"));
        autoModeChooser.addObject("Cheval Close Left", new A_Cheval("cleft"));
        autoModeChooser.addObject("Cheval Far Left", new A_Cheval("fleft"));
        
        autoModeChooser.addObject("Rough Terrain Center", new A_RoughTerrain("center"));
        autoModeChooser.addObject("Rough Terrain right", new A_RoughTerrain("right"));
        autoModeChooser.addObject("Rough Terrain Close Left", new A_RoughTerrain("cleft"));
        autoModeChooser.addObject("Rough Terrain Far Left", new A_RoughTerrain("fleft"));
        
        autoModeChooser.addObject("Low Bar", new A_Lowbar());
        
        SmartDashboard.putData("Auto Mode Chooser", autoModeChooser);
        
        
        
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
    	RobotMap.rotatorEncoder.reset();     // Have people put lift on bottom and reset it for consistency.
    	autonomousCommand = (Command) autoModeChooser.getSelected();
        autonomousCommand.start();
        if (autonomousCommand != null) autonomousCommand.start();
        }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to 
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        SmartDashboard.putBoolean("Lift on Top Limit", lift.getTopLimit());
        SmartDashboard.putNumber("Rotator Encoder Rotations", shooter.getDistance());
        SmartDashboard.putBoolean("Rotator on Bottom Limit", shooter.getBottomLimit());
        SmartDashboard.putNumber("Rotator Speed", shooter.getSpeed());
//      SmartDashboard.putNumber("Distance to Target", drivetrain.getDistance());
        SmartDashboard.putBoolean("Tomahawks Down", lift.getTomahawksDown());
        SmartDashboard.putNumber("Drivetrain Left Rotations", RobotMap.drivetrainLeftEncoder.getDistance());
        SmartDashboard.putNumber("Right Motor Rotations", RobotMap.drivetrainRightEncoder.getDistance());
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
}
